apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-premium-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain-sc
  resources:
    requests:
      storage: 5Gi
  